substitutions:
  name: "motion"
  friendly_name: "Motion"
  illuminance_update_interval: "2s"
  hidden_ssid: "false"
  log_level: DEBUG

#update:
#  - platform: http_request
#    id: update_http_request
#    name: Everything Presence Lite Firmware
#    source: https://everythingsmarthome.github.io/everything-presence-lite/everything-presence-lite-ha-manifest.json
#    disabled_by_default: true

dashboard_import:
  package_import_url: github://nikwest/everything-presence-lite/xiao-esp32c3-ld2410-ha.yaml@main
  import_full_config: false # or true

packages:
  device_base: !include
    file: common/xiao-esp32c3-base.yaml
    vars:
      led_pin: 2
      scl_pin: 9
      sda_pin: 8
  ld2410_base: !include
    file: common/ld2410-base.yaml
    vars:
      tx_pin: 5
      rx_pin: 4
  bluetooth_base: !include common/bluetooth-base.yaml
